/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import CSV.EscribirCSV;
import CSV.LeerCSV;
import Modelo.*;
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author LEFT4
 */
public class CargaAsigProfAlum extends javax.swing.JFrame {

    public void CargaComBox(){
        List<alumnos> listaAlumnos = new ArrayList<>();
        List<AsigProf> listaAsigProf = new ArrayList<>();
        
        listaAlumnos = LeerCSV.ImpAlumnosCSV();
        listaAsigProf = LeerCSV.ImpAsigProfCSV();
        
        String[] nombreAlum= new String[listaAlumnos.size()];  
        String[] Asig= new String[listaAsigProf.size()];
        String[] Mstr= new String[listaAsigProf.size()];
        for(int i=0;i< listaAlumnos.size();i++)
        {
            nombreAlum[i] = listaAlumnos.get(i).getNombre();
            
        }
        for(int j=0; j<listaAsigProf.size(); j++){
            Asig[j] = listaAsigProf.get(j).getNomAsig();
            Mstr[j] = listaAsigProf.get(j).getClaveM();
        }
        
//        System.out.println("WORKING");

        
        jComboBoxAlum.setModel(new javax.swing.DefaultComboBoxModel<>(nombreAlum));      
        ComboBoxAsigProf.setModel(new javax.swing.DefaultComboBoxModel<>(Asig));
        ComboBoxAsigProf2.setModel(new javax.swing.DefaultComboBoxModel<>(Mstr));
    }
    /**
     * Creates new form CargaAsigProfAlum
     */
    public CargaAsigProfAlum() {
        initComponents();
        setLocationRelativeTo(null);
        CargaComBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        jComboBoxAlum = new javax.swing.JComboBox<>();
        ComboBoxAsigProf = new javax.swing.JComboBox<>();
        CargarBT = new javax.swing.JButton();
        RegresarBT = new javax.swing.JButton();
        ComboBoxAsigProf2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Titulo.setText("Carga de Materias");

        jComboBoxAlum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ComboBoxAsigProf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CargarBT.setText("Cargar");
        CargarBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CargarBTMouseClicked(evt);
            }
        });

        RegresarBT.setText("Regresar");
        RegresarBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarBTMouseClicked(evt);
            }
        });

        ComboBoxAsigProf2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(Titulo)
                .addGap(83, 83, 83))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RegresarBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CargarBT)
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ComboBoxAsigProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ComboBoxAsigProf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(Titulo)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxAsigProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxAsigProf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CargarBT)
                    .addComponent(RegresarBT))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargarBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CargarBTMouseClicked
        List<AsigProfAlum> listaAsigProfAlum = new ArrayList();
        listaAsigProfAlum = LeerCSV.ImpAsigProfAlumCSV();
        String y1;
        String y2;
        String y3;
        y1 = (String) jComboBoxAlum.getSelectedItem();
        y2 = (String) ComboBoxAsigProf.getSelectedItem();
        y3 = (String) ComboBoxAsigProf2.getSelectedItem();
        AsigProfAlum register = new AsigProfAlum(y1, y2, y3);
        listaAsigProfAlum.add(register);
        EscribirCSV.ExpAsigProfAlumCSV(listaAsigProfAlum);
    }//GEN-LAST:event_CargarBTMouseClicked

    private void RegresarBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarBTMouseClicked
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegresarBTMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CargaAsigProfAlum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CargaAsigProfAlum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CargaAsigProfAlum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CargaAsigProfAlum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarBT;
    private javax.swing.JComboBox<String> ComboBoxAsigProf;
    private javax.swing.JComboBox<String> ComboBoxAsigProf2;
    private javax.swing.JButton RegresarBT;
    private javax.swing.JLabel Titulo;
    private javax.swing.JComboBox<String> jComboBoxAlum;
    // End of variables declaration//GEN-END:variables
}
