/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author LEFT4
 */
public class Datos extends javax.swing.JFrame {

    /**
     * Creates new form Datos
     */
    public Datos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        AsigTitulo = new javax.swing.JLabel();
        MaestrosTitulo = new javax.swing.JLabel();
        AlumTitulo = new javax.swing.JLabel();
        CargaBT1 = new javax.swing.JButton();
        CargaBT2 = new javax.swing.JButton();
        CargaBT3 = new javax.swing.JButton();
        AtrasBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Titulo.setText("DATOS");

        AsigTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AsigTitulo.setText("Asignaturas");

        MaestrosTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        MaestrosTitulo.setText("Maestros");

        AlumTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AlumTitulo.setText("Alumnos");

        CargaBT1.setText("Realizar Carga");
        CargaBT1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CargaBT1MouseClicked(evt);
            }
        });

        CargaBT2.setText("Realizar Carga");
        CargaBT2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CargaBT2MouseClicked(evt);
            }
        });

        CargaBT3.setText("Realizar Carga");
        CargaBT3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CargaBT3MouseClicked(evt);
            }
        });

        AtrasBT.setText("Atras");
        AtrasBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AtrasBTMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AsigTitulo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(AlumTitulo)
                        .addComponent(MaestrosTitulo)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CargaBT1)
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CargaBT2)
                            .addComponent(CargaBT3))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(Titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(AtrasBT)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Titulo)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AsigTitulo)
                    .addComponent(CargaBT1))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MaestrosTitulo)
                    .addComponent(CargaBT2))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AlumTitulo)
                    .addComponent(CargaBT3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(AtrasBT)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargaBT1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CargaBT1MouseClicked
        DatosAsig DA = new DatosAsig();
        DA.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CargaBT1MouseClicked

    private void CargaBT2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CargaBT2MouseClicked
        DatosMaestros DM = new DatosMaestros();
        DM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CargaBT2MouseClicked

    private void CargaBT3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CargaBT3MouseClicked
        DatosAlumnos DAlum = new DatosAlumnos();
        DAlum.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CargaBT3MouseClicked

    private void AtrasBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtrasBTMouseClicked
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AtrasBTMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Datos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlumTitulo;
    private javax.swing.JLabel AsigTitulo;
    private javax.swing.JButton AtrasBT;
    private javax.swing.JButton CargaBT1;
    private javax.swing.JButton CargaBT2;
    private javax.swing.JButton CargaBT3;
    private javax.swing.JLabel MaestrosTitulo;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
