/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author LEFT4
 */
public class Inicio extends javax.swing.JFrame {

    
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo1 = new javax.swing.JLabel();
        SubTitulo1 = new javax.swing.JLabel();
        SubTitulo2 = new javax.swing.JLabel();
        VerDatosBT = new javax.swing.JButton();
        AsignarBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Titulo1.setText("Control Escolar");

        SubTitulo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SubTitulo1.setText("Ver datos");

        SubTitulo2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SubTitulo2.setText("Asignar Maestros/Asignaturas");

        VerDatosBT.setText("Ver");
        VerDatosBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerDatosBTMouseClicked(evt);
            }
        });

        AsignarBT.setText("Asignar");
        AsignarBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AsignarBTMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Titulo1)
                .addGap(135, 135, 135))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(SubTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(SubTitulo2)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(VerDatosBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AsignarBT)
                .addGap(111, 111, 111))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(Titulo1)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubTitulo1)
                    .addComponent(SubTitulo2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VerDatosBT)
                    .addComponent(AsignarBT))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AsignarBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AsignarBTMouseClicked
        CargaAsigProf menu1 = new CargaAsigProf();
        menu1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AsignarBTMouseClicked

    private void VerDatosBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerDatosBTMouseClicked
        Datos D = new Datos();
        D.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VerDatosBTMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AsignarBT;
    private javax.swing.JLabel SubTitulo1;
    private javax.swing.JLabel SubTitulo2;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JButton VerDatosBT;
    // End of variables declaration//GEN-END:variables
}
